// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  usageKey: __t.string().name("usage_key"),
  roundId: __t.string().name("round_id"),
  participantId: __t.string().name("participant_id"),
  factCheckId: __t.string().name("fact_check_id"),
  usedAtMs: __t.i64().name("used_at_ms"),
});
