// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.string().primaryKey().name("room_id"),
  topic: __t.string(),
  teamALabel: __t.string().name("team_a_label"),
  teamBLabel: __t.string().name("team_b_label"),
  phase: __t.string(),
  round: __t.i32(),
  totalRounds: __t.i32().name("total_rounds"),
  scoreA: __t.i32().name("score_a"),
  scoreB: __t.i32().name("score_b"),
  speakerName: __t.string().name("speaker_name"),
  speakerSide: __t.string().name("speaker_side"),
  roundClaim: __t.string().name("round_claim"),
  players: __t.i32(),
  listeners: __t.i32(),
  winner: __t.string(),
  updatedAtMs: __t.i64().name("updated_at_ms"),
});
