// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  participantId: __t.string(),
  roomId: __t.string(),
  sessionId: __t.string(),
  displayName: __t.string(),
  role: __t.string(),
  queuePosition: __t.i32(),
  connected: __t.bool(),
  joinedAtMs: __t.i64(),
  timeUsedMs: __t.i64(),
};
