// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.string().primaryKey().name("room_id"),
  topic: __t.string(),
  status: __t.string(),
  teamALabel: __t.string().name("team_a_label"),
  teamBLabel: __t.string().name("team_b_label"),
  createdAtMs: __t.i64().name("created_at_ms"),
  turnSeconds: __t.i32().name("turn_seconds"),
  roundSeconds: __t.i32().name("round_seconds"),
  speakersPerTeamMax: __t.i32().name("speakers_per_team_max"),
});
