// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roundId: __t.string().primaryKey().name("round_id"),
  roomId: __t.string().name("room_id"),
  seq: __t.i32(),
  status: __t.string(),
  startedAtMs: __t.i64().name("started_at_ms"),
  endedAtMs: __t.i64().name("ended_at_ms"),
  roundDurationMs: __t.i64().name("round_duration_ms"),
  winner: __t.string(),
  finalScoreA: __t.i32().name("final_score_a"),
  finalScoreB: __t.i32().name("final_score_b"),
});
