// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  roomId: __t.string().name("room_id"),
  roundId: __t.string().name("round_id"),
  speakerId: __t.string().name("speaker_id"),
  side: __t.string(),
  text: __t.string(),
  createdAtMs: __t.i64().name("created_at_ms"),
});
