// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Claim = __t.object("Claim", {
  id: __t.string(),
  roomId: __t.string(),
  roundId: __t.string(),
  speakerId: __t.string(),
  side: __t.string(),
  claim: __t.string(),
  originalText: __t.string(),
  createdAtMs: __t.i64(),
});
export type Claim = __Infer<typeof Claim>;

export const ClaimIdea = __t.object("ClaimIdea", {
  claimId: __t.string(),
  roomId: __t.string(),
  roundId: __t.string(),
  speakerId: __t.string(),
  text: __t.string(),
  relevance: __t.f64(),
  admittedAtMs: __t.i64(),
  updatedAtMs: __t.i64(),
  evictedAtMs: __t.i64(),
});
export type ClaimIdea = __Infer<typeof ClaimIdea>;

export const FactCheck = __t.object("FactCheck", {
  id: __t.string(),
  roomId: __t.string(),
  roundId: __t.string(),
  challengerId: __t.string(),
  challengingSide: __t.string(),
  speakerId: __t.string(),
  speakerSide: __t.string(),
  claimId: __t.string(),
  claimText: __t.string(),
  status: __t.string(),
  finalVerdict: __t.string(),
  challengeOutcome: __t.string(),
  scoreDelta: __t.i32(),
  speakerRotated: __t.bool(),
  nextSpeakerId: __t.string(),
  createdAtMs: __t.i64(),
  resolvedAtMs: __t.i64(),
});
export type FactCheck = __Infer<typeof FactCheck>;

export const FactCheckUsage = __t.object("FactCheckUsage", {
  id: __t.u64(),
  usageKey: __t.string(),
  roundId: __t.string(),
  participantId: __t.string(),
  factCheckId: __t.string(),
  usedAtMs: __t.i64(),
});
export type FactCheckUsage = __Infer<typeof FactCheckUsage>;

export const FactCheckVote = __t.object("FactCheckVote", {
  id: __t.u64(),
  voteKey: __t.string(),
  factCheckId: __t.string(),
  provider: __t.string(),
  verdict: __t.string(),
  confidence: __t.f64(),
});
export type FactCheckVote = __Infer<typeof FactCheckVote>;

export const GameEvent = __t.object("GameEvent", {
  id: __t.u64(),
  roomId: __t.string(),
  roundId: __t.string(),
  type: __t.string(),
  participantId: __t.string(),
  side: __t.string(),
  points: __t.i32(),
  createdAtMs: __t.i64(),
});
export type GameEvent = __Infer<typeof GameEvent>;

export const GameState = __t.object("GameState", {
  roomId: __t.string(),
  roundId: __t.string(),
  phase: __t.string(),
  activeSide: __t.string(),
  activeSpeakerId: __t.string(),
  scoreA: __t.i32(),
  scoreB: __t.i32(),
  roundEndsAtMs: __t.i64(),
  roundRemainingMs: __t.i64(),
  speakerStartedAtMs: __t.i64(),
  readySpeakerId: __t.string(),
  readyEndsAtMs: __t.i64(),
  activeFactCheckId: __t.string(),
  paused: __t.bool(),
});
export type GameState = __Infer<typeof GameState>;

export const Participant = __t.object("Participant", {
  participantId: __t.string(),
  roomId: __t.string(),
  displayName: __t.string(),
  role: __t.string(),
  queuePosition: __t.i32(),
  connected: __t.bool(),
  joinedAtMs: __t.i64(),
  timeUsedMs: __t.i64(),
});
export type Participant = __Infer<typeof Participant>;

export const ParticipantSecret = __t.object("ParticipantSecret", {
  participantId: __t.string(),
  sessionId: __t.string(),
});
export type ParticipantSecret = __Infer<typeof ParticipantSecret>;

export const Room = __t.object("Room", {
  roomId: __t.string(),
  topic: __t.string(),
  status: __t.string(),
  teamALabel: __t.string(),
  teamBLabel: __t.string(),
  createdAtMs: __t.i64(),
  turnSeconds: __t.i32(),
  roundSeconds: __t.i32(),
  speakersPerTeamMax: __t.i32(),
});
export type Room = __Infer<typeof Room>;

export const RoomSecret = __t.object("RoomSecret", {
  roomId: __t.string(),
  hostToken: __t.string(),
  hostParticipantId: __t.string(),
});
export type RoomSecret = __Infer<typeof RoomSecret>;

export const Round = __t.object("Round", {
  roundId: __t.string(),
  roomId: __t.string(),
  seq: __t.i32(),
  status: __t.string(),
  startedAtMs: __t.i64(),
  endedAtMs: __t.i64(),
  roundDurationMs: __t.i64(),
  winner: __t.string(),
  finalScoreA: __t.i32(),
  finalScoreB: __t.i32(),
});
export type Round = __Infer<typeof Round>;

export const ScheduleReady = __t.object("ScheduleReady", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomId: __t.string(),
});
export type ScheduleReady = __Infer<typeof ScheduleReady>;

export const ScheduleRound = __t.object("ScheduleRound", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomId: __t.string(),
});
export type ScheduleRound = __Infer<typeof ScheduleRound>;

export const SpeakerQueue = __t.object("SpeakerQueue", {
  id: __t.u64(),
  queueKey: __t.string(),
  roundId: __t.string(),
  side: __t.string(),
  position: __t.i32(),
  participantId: __t.string(),
});
export type SpeakerQueue = __Infer<typeof SpeakerQueue>;

export const SpeakerState = __t.object("SpeakerState", {
  id: __t.u64(),
  stateKey: __t.string(),
  roundId: __t.string(),
  participantId: __t.string(),
  remainingMs: __t.i64(),
});
export type SpeakerState = __Infer<typeof SpeakerState>;

export const TranscriptSegment = __t.object("TranscriptSegment", {
  id: __t.string(),
  roomId: __t.string(),
  roundId: __t.string(),
  speakerId: __t.string(),
  side: __t.string(),
  text: __t.string(),
  createdAtMs: __t.i64(),
});
export type TranscriptSegment = __Infer<typeof TranscriptSegment>;

