// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddClaimReducer from "../add_claim_reducer";
import AppendTranscriptReducer from "../append_transcript_reducer";
import ContinueVerdictReducer from "../continue_verdict_reducer";
import CreateRoomReducer from "../create_room_reducer";
import EndRoundReducer from "../end_round_reducer";
import JoinRoomReducer from "../join_room_reducer";
import RecordClaimReducer from "../record_claim_reducer";
import RecordFactCheckReducer from "../record_fact_check_reducer";
import RecordParticipantReducer from "../record_participant_reducer";
import RecordRoomReducer from "../record_room_reducer";
import RecordRoundReducer from "../record_round_reducer";
import RecordTranscriptReducer from "../record_transcript_reducer";
import ResolveFactCheckReducer from "../resolve_fact_check_reducer";
import SetRoleReducer from "../set_role_reducer";
import StartRoundReducer from "../start_round_reducer";
import SubmitFactCheckReducer from "../submit_fact_check_reducer";

export type AddClaimParams = __Infer<typeof AddClaimReducer>;
export type AppendTranscriptParams = __Infer<typeof AppendTranscriptReducer>;
export type ContinueVerdictParams = __Infer<typeof ContinueVerdictReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type EndRoundParams = __Infer<typeof EndRoundReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type RecordClaimParams = __Infer<typeof RecordClaimReducer>;
export type RecordFactCheckParams = __Infer<typeof RecordFactCheckReducer>;
export type RecordParticipantParams = __Infer<typeof RecordParticipantReducer>;
export type RecordRoomParams = __Infer<typeof RecordRoomReducer>;
export type RecordRoundParams = __Infer<typeof RecordRoundReducer>;
export type RecordTranscriptParams = __Infer<typeof RecordTranscriptReducer>;
export type ResolveFactCheckParams = __Infer<typeof ResolveFactCheckReducer>;
export type SetRoleParams = __Infer<typeof SetRoleReducer>;
export type StartRoundParams = __Infer<typeof StartRoundReducer>;
export type SubmitFactCheckParams = __Infer<typeof SubmitFactCheckReducer>;

