// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  claimId: __t.string().primaryKey().name("claim_id"),
  roomId: __t.string().name("room_id"),
  roundId: __t.string().name("round_id"),
  speakerId: __t.string().name("speaker_id"),
  text: __t.string(),
  relevance: __t.f64(),
  admittedAtMs: __t.i64().name("admitted_at_ms"),
  updatedAtMs: __t.i64().name("updated_at_ms"),
  evictedAtMs: __t.i64().name("evicted_at_ms"),
});
