// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  roomId: __t.string().name("room_id"),
  roundId: __t.string().name("round_id"),
  challengerId: __t.string().name("challenger_id"),
  challengingSide: __t.string().name("challenging_side"),
  speakerId: __t.string().name("speaker_id"),
  speakerSide: __t.string().name("speaker_side"),
  claimId: __t.string().name("claim_id"),
  claimText: __t.string().name("claim_text"),
  status: __t.string(),
  finalVerdict: __t.string().name("final_verdict"),
  challengeOutcome: __t.string().name("challenge_outcome"),
  scoreDelta: __t.i32().name("score_delta"),
  speakerRotated: __t.bool().name("speaker_rotated"),
  nextSpeakerId: __t.string().name("next_speaker_id"),
  createdAtMs: __t.i64().name("created_at_ms"),
  resolvedAtMs: __t.i64().name("resolved_at_ms"),
});
