// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.string().primaryKey().name("room_id"),
  roundId: __t.string().name("round_id"),
  phase: __t.string(),
  activeSide: __t.string().name("active_side"),
  activeSpeakerId: __t.string().name("active_speaker_id"),
  scoreA: __t.i32().name("score_a"),
  scoreB: __t.i32().name("score_b"),
  roundEndsAtMs: __t.i64().name("round_ends_at_ms"),
  roundRemainingMs: __t.i64().name("round_remaining_ms"),
  speakerStartedAtMs: __t.i64().name("speaker_started_at_ms"),
  readySpeakerId: __t.string().name("ready_speaker_id"),
  readyEndsAtMs: __t.i64().name("ready_ends_at_ms"),
  activeFactCheckId: __t.string().name("active_fact_check_id"),
  paused: __t.bool(),
});
