// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddClaimReducer from "./add_claim_reducer";
import AppendTranscriptReducer from "./append_transcript_reducer";
import ContinueVerdictReducer from "./continue_verdict_reducer";
import CreateRoomReducer from "./create_room_reducer";
import EndRoundReducer from "./end_round_reducer";
import JoinRoomReducer from "./join_room_reducer";
import RecordClaimReducer from "./record_claim_reducer";
import RecordClaimIdeaReducer from "./record_claim_idea_reducer";
import RecordFactCheckReducer from "./record_fact_check_reducer";
import RecordParticipantReducer from "./record_participant_reducer";
import RecordRoomReducer from "./record_room_reducer";
import RecordRoundReducer from "./record_round_reducer";
import RecordTranscriptReducer from "./record_transcript_reducer";
import ResolveFactCheckReducer from "./resolve_fact_check_reducer";
import SetRoleReducer from "./set_role_reducer";
import StartRoundReducer from "./start_round_reducer";
import SubmitFactCheckReducer from "./submit_fact_check_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ClaimRow from "./claim_table";
import ClaimIdeaRow from "./claim_idea_table";
import FactCheckRow from "./fact_check_table";
import FactCheckUsageRow from "./fact_check_usage_table";
import FactCheckVoteRow from "./fact_check_vote_table";
import GameEventRow from "./game_event_table";
import GameStateRow from "./game_state_table";
import ParticipantRow from "./participant_table";
import RoomRow from "./room_table";
import RoundRow from "./round_table";
import SpeakerQueueRow from "./speaker_queue_table";
import SpeakerStateRow from "./speaker_state_table";
import TranscriptSegmentRow from "./transcript_segment_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  claim: __table({
    name: 'claim',
    indexes: [
      { accessor: 'id', name: 'claim_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_round_speaker', name: 'claim_round_id_speaker_id_idx_btree', algorithm: 'btree', columns: [
        'roundId',
        'speakerId',
      ] },
    ],
    constraints: [
      { name: 'claim_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClaimRow),
  claimIdea: __table({
    name: 'claim_idea',
    indexes: [
      { accessor: 'claimId', name: 'claim_idea_claim_id_idx_btree', algorithm: 'btree', columns: [
        'claimId',
      ] },
      { accessor: 'by_round_speaker', name: 'claim_idea_round_id_speaker_id_idx_btree', algorithm: 'btree', columns: [
        'roundId',
        'speakerId',
      ] },
    ],
    constraints: [
      { name: 'claim_idea_claim_id_key', constraint: 'unique', columns: ['claimId'] },
    ],
  }, ClaimIdeaRow),
  factCheck: __table({
    name: 'fact_check',
    indexes: [
      { accessor: 'id', name: 'fact_check_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_round', name: 'fact_check_round_id_idx_btree', algorithm: 'btree', columns: [
        'roundId',
      ] },
    ],
    constraints: [
      { name: 'fact_check_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FactCheckRow),
  factCheckUsage: __table({
    name: 'fact_check_usage',
    indexes: [
      { accessor: 'id', name: 'fact_check_usage_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'usageKey', name: 'fact_check_usage_usage_key_idx_btree', algorithm: 'btree', columns: [
        'usageKey',
      ] },
    ],
    constraints: [
      { name: 'fact_check_usage_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'fact_check_usage_usage_key_key', constraint: 'unique', columns: ['usageKey'] },
    ],
  }, FactCheckUsageRow),
  factCheckVote: __table({
    name: 'fact_check_vote',
    indexes: [
      { accessor: 'by_check', name: 'fact_check_vote_fact_check_id_idx_btree', algorithm: 'btree', columns: [
        'factCheckId',
      ] },
      { accessor: 'id', name: 'fact_check_vote_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'voteKey', name: 'fact_check_vote_vote_key_idx_btree', algorithm: 'btree', columns: [
        'voteKey',
      ] },
    ],
    constraints: [
      { name: 'fact_check_vote_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'fact_check_vote_vote_key_key', constraint: 'unique', columns: ['voteKey'] },
    ],
  }, FactCheckVoteRow),
  gameEvent: __table({
    name: 'game_event',
    indexes: [
      { accessor: 'id', name: 'game_event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_room', name: 'game_event_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'game_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameEventRow),
  gameState: __table({
    name: 'game_state',
    indexes: [
      { accessor: 'roomId', name: 'game_state_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'game_state_room_id_key', constraint: 'unique', columns: ['roomId'] },
    ],
  }, GameStateRow),
  participant: __table({
    name: 'participant',
    indexes: [
      { accessor: 'participantId', name: 'participant_participant_id_idx_btree', algorithm: 'btree', columns: [
        'participantId',
      ] },
      { accessor: 'by_room', name: 'participant_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'participant_participant_id_key', constraint: 'unique', columns: ['participantId'] },
    ],
  }, ParticipantRow),
  room: __table({
    name: 'room',
    indexes: [
      { accessor: 'roomId', name: 'room_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'room_room_id_key', constraint: 'unique', columns: ['roomId'] },
    ],
  }, RoomRow),
  round: __table({
    name: 'round',
    indexes: [
      { accessor: 'by_room', name: 'round_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
      { accessor: 'roundId', name: 'round_round_id_idx_btree', algorithm: 'btree', columns: [
        'roundId',
      ] },
    ],
    constraints: [
      { name: 'round_round_id_key', constraint: 'unique', columns: ['roundId'] },
    ],
  }, RoundRow),
  speakerQueue: __table({
    name: 'speaker_queue',
    indexes: [
      { accessor: 'id', name: 'speaker_queue_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'queueKey', name: 'speaker_queue_queue_key_idx_btree', algorithm: 'btree', columns: [
        'queueKey',
      ] },
      { accessor: 'by_round_side', name: 'speaker_queue_round_id_side_idx_btree', algorithm: 'btree', columns: [
        'roundId',
        'side',
      ] },
    ],
    constraints: [
      { name: 'speaker_queue_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'speaker_queue_queue_key_key', constraint: 'unique', columns: ['queueKey'] },
    ],
  }, SpeakerQueueRow),
  speakerState: __table({
    name: 'speaker_state',
    indexes: [
      { accessor: 'id', name: 'speaker_state_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_round', name: 'speaker_state_round_id_idx_btree', algorithm: 'btree', columns: [
        'roundId',
      ] },
      { accessor: 'stateKey', name: 'speaker_state_state_key_idx_btree', algorithm: 'btree', columns: [
        'stateKey',
      ] },
    ],
    constraints: [
      { name: 'speaker_state_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'speaker_state_state_key_key', constraint: 'unique', columns: ['stateKey'] },
    ],
  }, SpeakerStateRow),
  transcriptSegment: __table({
    name: 'transcript_segment',
    indexes: [
      { accessor: 'id', name: 'transcript_segment_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_round', name: 'transcript_segment_round_id_idx_btree', algorithm: 'btree', columns: [
        'roundId',
      ] },
    ],
    constraints: [
      { name: 'transcript_segment_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TranscriptSegmentRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_claim", AddClaimReducer),
  __reducerSchema("append_transcript", AppendTranscriptReducer),
  __reducerSchema("continue_verdict", ContinueVerdictReducer),
  __reducerSchema("create_room", CreateRoomReducer),
  __reducerSchema("end_round", EndRoundReducer),
  __reducerSchema("join_room", JoinRoomReducer),
  __reducerSchema("record_claim", RecordClaimReducer),
  __reducerSchema("record_claim_idea", RecordClaimIdeaReducer),
  __reducerSchema("record_fact_check", RecordFactCheckReducer),
  __reducerSchema("record_participant", RecordParticipantReducer),
  __reducerSchema("record_room", RecordRoomReducer),
  __reducerSchema("record_round", RecordRoundReducer),
  __reducerSchema("record_transcript", RecordTranscriptReducer),
  __reducerSchema("resolve_fact_check", ResolveFactCheckReducer),
  __reducerSchema("set_role", SetRoleReducer),
  __reducerSchema("start_round", StartRoundReducer),
  __reducerSchema("submit_fact_check", SubmitFactCheckReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

