// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  participantId: __t.string().primaryKey().name("participant_id"),
  roomId: __t.string().name("room_id"),
  displayName: __t.string().name("display_name"),
  role: __t.string(),
  queuePosition: __t.i32().name("queue_position"),
  connected: __t.bool(),
  joinedAtMs: __t.i64().name("joined_at_ms"),
  timeUsedMs: __t.i64().name("time_used_ms"),
});
