// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  roundId: __t.string(),
  roomId: __t.string(),
  seq: __t.i32(),
  status: __t.string(),
  startedAtMs: __t.i64(),
  endedAtMs: __t.i64(),
  roundDurationMs: __t.i64(),
  winner: __t.string(),
  scoreA: __t.i32(),
  scoreB: __t.i32(),
  phase: __t.string(),
};
