// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  roomId: __t.string(),
  roundId: __t.string(),
  challengerId: __t.string(),
  challengingSide: __t.string(),
  speakerId: __t.string(),
  speakerSide: __t.string(),
  claimId: __t.string(),
  claimText: __t.string(),
  status: __t.string(),
  finalVerdict: __t.string(),
  challengeOutcome: __t.string(),
  scoreDelta: __t.i32(),
  scoreA: __t.i32(),
  scoreB: __t.i32(),
  createdAtMs: __t.i64(),
  resolvedAtMs: __t.i64(),
  geminiVerdict: __t.string(),
  geminiConfidence: __t.f64(),
  claudeVerdict: __t.string(),
  claudeConfidence: __t.f64(),
};
