// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  roomId: __t.string(),
  topic: __t.string(),
  status: __t.string(),
  teamALabel: __t.string(),
  teamBLabel: __t.string(),
  hostToken: __t.string(),
  hostParticipantId: __t.string(),
  createdAtMs: __t.i64(),
  turnSeconds: __t.i32(),
  roundSeconds: __t.i32(),
  speakersPerTeamMax: __t.i32(),
};
