// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  claimId: __t.string(),
  roomId: __t.string(),
  roundId: __t.string(),
  speakerId: __t.string(),
  text: __t.string(),
  relevance: __t.f64(),
  admittedAtMs: __t.i64(),
  updatedAtMs: __t.i64(),
  evictedAtMs: __t.i64(),
};
