// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  factCheckId: __t.string(),
  finalVerdict: __t.string(),
  geminiVerdict: __t.string(),
  geminiConfidence: __t.f64(),
  claudeVerdict: __t.string(),
  claudeConfidence: __t.f64(),
};
