// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  roomId: __t.string(),
  topic: __t.string(),
  teamALabel: __t.string(),
  teamBLabel: __t.string(),
  phase: __t.string(),
  round: __t.i32(),
  totalRounds: __t.i32(),
  scoreA: __t.i32(),
  scoreB: __t.i32(),
  speakerName: __t.string(),
  speakerSide: __t.string(),
  roundClaim: __t.string(),
  players: __t.i32(),
  listeners: __t.i32(),
  winner: __t.string(),
  updatedAtMs: __t.i64(),
};
